export const ACTION_TYPES = {
  DISPLAY_ALERT: 'SHOW_ALERT',
  CLEAR_ALERT: 'CLEAR_ALERT',

  AUTHENTICATE_USER_START: 'AUTHENTICATE_USER_START',
  AUTHENTICATE_USER_SUCCESS: 'AUTHENTICATE_USER_SUCCESS',
  AUTHENTICATE_USER_ERROR: 'AUTHENTICATE_USER_ERROR',
};
