export const ACTION_TYPES = {
  DISPLAY_ALERT: 'SHOW_ALERT',
  CLEAR_ALERT: 'CLEAR_ALERT',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',

  AUTHENTICATE_USER_START: 'AUTHENTICATE_USER_START',
  AUTHENTICATE_USER_SUCCESS: 'AUTHENTICATE_USER_SUCCESS',
  AUTHENTICATE_USER_ERROR: 'AUTHENTICATE_USER_ERROR',

  LOG_OUT_USER: 'LOG_OUT_USER',
};
