export const ACTION_TYPES = {
  DISPLAY_ALERT: 'SHOW_ALERT',
  CLEAR_ALERT: 'CLEAR_ALERT',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',

  AUTHENTICATE_USER_START: 'AUTHENTICATE_USER_START',
  AUTHENTICATE_USER_SUCCESS: 'AUTHENTICATE_USER_SUCCESS',
  AUTHENTICATE_USER_ERROR: 'AUTHENTICATE_USER_ERROR',

  UPDATE_USER_START: 'UPDATE_USER_START',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',

  HANDLE_CHANGE: 'HANDLE_CHANGE',
  CLEAR_VALUES: 'CLEAR_VALUES',

  CREATE_JOB_BEGIN: 'CREATE_JOB_BEGIN',
  CREATE_JOB_SUCCESS: 'CREATE_JOB_SUCCESS',
  CREATE_JOB_ERROR: 'CREATE_JOB_ERROR',

  EDIT_JOB_BEGIN: 'EDIT_JOB_BEGIN',
  EDIT_JOB_SUCCESS: 'EDIT_JOB_SUCCESS',
  EDIT_JOB_ERROR: 'EDIT_JOB_ERROR',

  DELETE_JOB_BEGIN: 'DELETE_JOB_BEGIN',

  GET_JOBS_BEGIN: 'GET_JOB_BEGIN',
  GET_JOBS_SUCCESS: 'GET_JOB_SUCCESS',

  SET_EDIT_JOB: 'SET_EDIT_JOB',

  LOG_OUT_USER: 'LOG_OUT_USER',
};
